// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuU5lR6dtzT_uJgDArxOgKtOFdX7B-piU',
    appId: '1:1004401762155:web:fbf892fbd0c479445cf62e',
    messagingSenderId: '1004401762155',
    projectId: 'safebite-f5e89',
    authDomain: 'safebite-f5e89.firebaseapp.com',
    storageBucket: 'safebite-f5e89.firebasestorage.app',
    measurementId: 'G-Y5WZQJYRDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNVnnoKOXvki2GE7WwvH8AUBqwl6svb4',
    appId: '1:1004401762155:android:8eeda5c72a68afe75cf62e',
    messagingSenderId: '1004401762155',
    projectId: 'safebite-f5e89',
    storageBucket: 'safebite-f5e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hbLNjtw70g0W6PZKyxlO9W1Z9Vvbjas',
    appId: '1:1004401762155:ios:e64981f70735c1595cf62e',
    messagingSenderId: '1004401762155',
    projectId: 'safebite-f5e89',
    storageBucket: 'safebite-f5e89.firebasestorage.app',
    iosClientId: '1004401762155-sct89f2i4o5268nbpukg7l8f19m82nnu.apps.googleusercontent.com',
    iosBundleId: 'com.skstudio.safebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hbLNjtw70g0W6PZKyxlO9W1Z9Vvbjas',
    appId: '1:1004401762155:ios:e64981f70735c1595cf62e',
    messagingSenderId: '1004401762155',
    projectId: 'safebite-f5e89',
    storageBucket: 'safebite-f5e89.firebasestorage.app',
    iosClientId: '1004401762155-sct89f2i4o5268nbpukg7l8f19m82nnu.apps.googleusercontent.com',
    iosBundleId: 'com.skstudio.safebite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuU5lR6dtzT_uJgDArxOgKtOFdX7B-piU',
    appId: '1:1004401762155:web:8b3749116c6b99825cf62e',
    messagingSenderId: '1004401762155',
    projectId: 'safebite-f5e89',
    authDomain: 'safebite-f5e89.firebaseapp.com',
    storageBucket: 'safebite-f5e89.firebasestorage.app',
    measurementId: 'G-NQ61JYWG8J',
  );
}
